# Generated by Django 4.2.5 on 2023-10-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="description",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="price",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_brand",
            field=models.CharField(default="mahindra", max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_description",
            field=models.CharField(default="good", max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_features",
            field=models.CharField(default="best car for offroad", max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_fuel",
            field=models.CharField(default="diesel", max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_luggage",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_mileage",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_model",
            field=models.CharField(default="2021", max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_price",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_seats",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="c_transmission",
            field=models.CharField(default="Automatic", max_length=100),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="c_name",
            field=models.CharField(default="Thar", max_length=100),
        ),
    ]
